#!/usr/bin/env python3
"""Collect derived words from generated docs into an extra vocabulary.

These words are derivation/association words produced by the AI docs and are
not part of the 考研 outline, so they are marked inOutline=false.
"""

from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

NETEM_URL = (
    "https://raw.githubusercontent.com/exam-data/NETEMVocabulary/"
    "master/netem_full_list.json"
)
ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = ROOT / "output"
OUT_FILE = ROOT / "src" / "data" / "vocabulary-extra.js"
EXTRA_ID_START = 60000

DERIVED_LINE = re.compile(
    r"^\s*[├└]──\s*([A-Za-z][A-Za-z'’-]*)\s*\(([^)]*)\)"
)
VALID_WORD = re.compile(r"^[A-Za-z][A-Za-z'’-]*$")


def fetch_main_words() -> set[str]:
    request = urllib.request.Request(NETEM_URL, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(request, timeout=60) as response:
        payload = json.loads(response.read().decode("utf-8"))
    rows = next(iter(payload.values())) if isinstance(payload, dict) else payload
    return {str(row.get("单词", "")).lower() for row in rows if row.get("单词")}


def js_safe(text: str) -> str:
    return text.replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")


def collect_entries(main_words: set[str]) -> list[dict]:
    entries: list[dict] = []
    seen: set[str] = set()
    for path in sorted(DOCS_DIR.glob("Day_*.md")):
        try:
            day = int(path.stem.split("_")[1])
        except (IndexError, ValueError):
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            match = DERIVED_LINE.match(line)
            if not match:
                continue
            word = match.group(1)
            meaning = match.group(2).strip()
            key = word.lower()
            if not meaning or not VALID_WORD.fullmatch(word):
                continue
            if key in main_words or key in seen:
                continue
            seen.add(key)
            entries.append(
                {
                    "id": EXTRA_ID_START + len(entries),
                    "word": word,
                    "phonetic": "",
                    "meaning": meaning,
                    "example": "",
                    "exampleCn": "",
                    "frequency": None,
                    "category": "",
                    "subcategory": "",
                    "alternate": None,
                    "meanings": [],
                    "phrases": [],
                    "inOutline": False,
                    "sourceDay": day,
                }
            )
    return entries


def main() -> None:
    main_words = fetch_main_words()
    entries = collect_entries(main_words)
    body = js_safe(json.dumps(entries, ensure_ascii=False, indent=2))
    content = (
        "// Generated by scripts/build_extra_vocabulary.py from "
        "output/Day_*.md. Do not edit.\n"
        "const vocabulary = "
        + body
        + ";\n\nexport default vocabulary;\n"
    )
    OUT_FILE.write_text(content, encoding="utf-8")
    print(f"extra vocabulary: {len(entries)} words -> {OUT_FILE}")


if __name__ == "__main__":
    main()
