#!/usr/bin/env python3
"""Download the NETEM vocabulary list and regenerate the app's data files.

Data source: https://github.com/exam-data/NETEMVocabulary
"""

from __future__ import annotations

import json
import urllib.request
from pathlib import Path

DATA_URL = (
    "https://raw.githubusercontent.com/exam-data/NETEMVocabulary/"
    "master/netem_full_list.json"
)
KAOYAN_URL = (
    "https://raw.githubusercontent.com/vxiaozhi/vocabulary-book-by-deepseek/"
    "main/data/kaoyan/kaoyan-words.json"
)
CHUNK_SIZE = 500
MAX_PHRASES = 8
ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "src" / "data"


def fetch_json(url: str):
    request = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return json.loads(response.read().decode("utf-8"))


def fetch_rows() -> list[dict]:
    """Fetch the NETEM word list. Its JSON is a dict whose only value is a list."""
    payload = fetch_json(DATA_URL)
    if isinstance(payload, dict):
        return next(iter(payload.values()))
    return payload


def fetch_kaoyan_map() -> dict[str, dict]:
    """Fetch vxiaozhi/vocabulary-book-by-deepseek kaoyan data for rich meanings."""
    rows = fetch_json(KAOYAN_URL)
    return {
        str(row.get("word", "")).lower(): row
        for row in rows
        if row.get("word")
    }


def to_entry(row: dict, kaoyan_map: dict[str, dict]) -> dict:
    word = row.get("单词", "")
    extra = kaoyan_map.get(word.lower(), {})
    return {
        "id": row.get("序号"),
        "word": word,
        "phonetic": "",
        "meaning": row.get("释义", ""),
        "example": "",
        "exampleCn": "",
        "frequency": row.get("词频"),
        "category": row.get("分类"),
        "subcategory": row.get("子分类"),
        "alternate": row.get("其他拼写"),
        "meanings": extra.get("translations", []),
        "phrases": extra.get("phrases", [])[:MAX_PHRASES],
    }


def js_safe(text: str) -> str:
    # U+2028/U+2029 are valid JSON but were historically invalid in JS strings.
    return text.replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")


def write_chunks(entries: list[dict]) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    chunk_files = []
    for index in range(0, len(entries), CHUNK_SIZE):
        chunk = entries[index : index + CHUNK_SIZE]
        part = index // CHUNK_SIZE + 1
        filename = OUT_DIR / f"vocabulary-{part}.js"
        body = js_safe(json.dumps(chunk, ensure_ascii=False, indent=2))
        content = (
            "// Generated by scripts/update_vocabulary.py from "
            "exam-data/NETEMVocabulary. Do not edit.\n"
            "const vocabulary = "
            + body
            + ";\n\nexport default vocabulary;\n"
        )
        filename.write_text(content, encoding="utf-8")
        chunk_files.append((part, filename, len(chunk)))

    imports = "\n".join(
        f"import part{part} from './vocabulary-{part}';" for part, _, _ in chunk_files
    )
    spread = "".join(f"...part{part}, " for part, _, _ in chunk_files).rstrip(", ")
    aggregator = (
        "// Generated by scripts/update_vocabulary.py from "
        "exam-data/NETEMVocabulary. Do not edit.\n"
        f"{imports}\n"
        "import extra from './vocabulary-extra';\n\n"
        f"const vocabulary = [{spread}, ...extra];\n\n"
        "export default vocabulary;\n"
    )
    (OUT_DIR / "vocabulary.js").write_text(aggregator, encoding="utf-8")

    for part, filename, count in chunk_files:
        print(f"wrote {filename.name} ({count} words)")


def main() -> None:
    rows = fetch_rows()
    kaoyan_map = fetch_kaoyan_map()
    entries = [
        to_entry(row, kaoyan_map)
        for row in rows
        if row.get("单词") and row.get("释义")
    ]
    enriched = sum(1 for e in entries if e["meanings"])
    print(
        f"downloaded {len(rows)} rows, mapped {len(entries)} entries, "
        f"enriched {enriched} with kaoyan meanings"
    )
    write_chunks(entries)
    print(f"done: {OUT_DIR}")


if __name__ == "__main__":
    main()
